version: '3'
services:
    db:
        image: mariadb
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: imgroot
            MYSQL_DATABASE: mod_db
            MYSQL_USER: mod_user
            MYSQL_PASSWORD: sukses123
    webserver:
        image: nginx
        ports: 
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/site.conf
            - ./moodledata:/code/moodledata:rw
    php:
        build:
            ./
        volumes:
            - ./code:/code