version: '3'
services:
    webserver:
        image: nginx
        ports: 
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/site.conf
            - ./moodledata:/moodledata
    php:
        build:
            ./
        volumes:
            - ./code:/code